const iphone = [
  {
    name: "New Apple iPhone 13",
    price: 15800,
    colors: ["blue", "midnight", "red"],
    size: "128",
    memory: "128",
    operating_system: "IOS 14",
    colour: "Midnight",
    model_year: 2021,
    included: "USB-C ",
    images: "/products/iphones/ph13/ph13-blue.jpg",
    img:'ph13',
    quantity:5

},
  {
    name: "Apple iPhone 13 Pro Max",
    price: 24.598,
    colors: ["gold", "silver", "blue"],
    size: "256",
    memory: "256",
    operating_system: "IOS 14",
    colour: "silver",
    model_year: 2021,
    included: "USB-C", 
    images: "/products/iphones/phpro3/phpro13-gold.jpg",
    img:'ph13pro',
    quantity:4
},{
    name: "Apple iPhone 12",
    price: 14450,
    colors: ["black", "green", "white"],
    size: "128",
    memory: "128 ",
    operating_system: "IOS 14",
    colour: Midnight,
    model_year: 2020,
    included: "USB-C ",
    images: "/products/iphones/ph12/ph12-white.jpg",
    img:'ph12',
    quantity:6
},{
    name: "Apple iPhone 12 Pro",
    price: 18440,
    colors: ["gold", "blue", "silver"],
    size: "128",
    memory: "128 ",
    operating_system: "IOS 14",
    colour: "blue",
    model_year: 2020,
    included: "USB-C ",
    images: "/products/iphones/ph12pro/ph12pro-white.jpg",
    img:'ph12pro',
    quantity:2

  },{
    name: "Apple iPhone 11",
    price: 12200,
    colors: ["black", "red", "white"],
    size: "128",
    memory: "128",
    operating_system: "IOS 14",
    colour: "black",
    model_year: 2019,
    included: "USB-C ",
    images: "/products/iphones/ph11/ph11-white.jpg",
    img:'ph11',
    quantity:8
  },{
    name: "Apple iPhone 7",
    price: 5999,
    colors: ["black"],
    size: "128", 
    memory: "128",
    operating_system: "IOS",
    colour: "black",
    model_year: 2018,
    included: "USB",
    img:"ph7",
    quantity:0
  },{
    name: "Apple iPhone 8",
    price: 7350,
    colors: ["gold"],
    size: "64",
    memory: "64 ",
    operating_system: "IOS",
    colour: "gold",
    model_year: 2019,
    included: "USB-C ",
    img:"ph8",
    quantity:1
  },{
    name: "Apple iPhone 8 Plus",
    price: 8999,
    colors: ["gold"],
    size: "64",
    memory: "64",
    operating_system: "IOS",
    colour: "gold",
    model_year: 2019,
    included: "USB-C ",
    img:"ph8pro",
    quantity:10
  },{
    name: "iPhone 11 Pro Max",
    price: 20000,
    colors: ["gold", "green", "silver"],
    size: "512",
    memory: "512 ",
    operating_system: "IOS",
    colour: "gold",
    model_year: 2021,
    included: "USB-C ",
    img:"ph11prom",
    quantity:6
  }]