const dataIphones = [
  {
    name: "New Apple iPhone 13",
    price: 15800,
    colors: ["blue", "midnight", "red"],
    size: "128",
    memory: "128",
    operating_system: "IOS 14",
    colour: "Midnight",
    model_year: 2021,
    included: "USB-C ",
    Discounting: 15,
    images: "/products/iphones/ph13/ph13-rose.jpg",
    img: "ph13",
    quantity: 5,
    rate: 4.5,
  },
  {
    name: "Apple iPhone 13 Pro Max",
    price: 24598,
    colors: ["gold", "silver", "blue"],
    size: "256",
    memory: "256",
    operating_system: "IOS 14",
    colour: "silver",
    model_year: 2021,
    included: "USB-C ",
    Discounting: 15,
    images: "/products/iphones/ph13pro/ph13pro-gold.jpg",
    img: "ph13pro",
    quantity: 4,
    rate:"1.5"
  },
  {
    name: "Apple iPhone 12",
    price: 14450,
    colors: ["black", "green", "white"],
    size: "128",
    memory: "128 ",
    operating_system: "IOS 14",
    colour: "Midnight",
    model_year: 2020,
    included: "USB-C ",
    Discounting: 12,
    rate: 3.5,
    images: "/products/iphones/ph12/ph12-white.jpg",
    img: "ph12",
    quantity: 6,
  },
  {
    name: "Apple iPhone 12 Pro",
    price: 18440,
    colors: ["gold", "blue", "silver"],
    size: "128",
    memory: "128 ",
    operating_system: "IOS 14",
    colour: "blue",
    model_year: 2020,
    included: "USB-C ",
    Discounting: 12,
    rate: 3.5,
    images: "/products/iphones/ph12pro/ph12pro-blue.jpg",
    img: "ph12pro",
    quantity: 2,
  },
  {
    name: "Apple iPhone 11",
    price: 12200,
    colors: ["black", "red", "white"],
    size: "128",
    memory: "128",
    operating_system: "IOS 14",
    colour: "black",
    model_year: 2019,
    included: "USB-C ",
    Discounting: 12,
    rate: 3.5,
    images: "/products/iphones/ph11/ph11-white.jpg",
    img: "ph11",
    quantity: 8,
  },
  {
    name: "Apple iPhone 7",
    price: 5999,
    colors: ["black"],
    size: "128",
    memory: "128",
    operating_system: "IOS",
    colour: "black",
    model_year: 2018,
    included: "USB-C ",
    Discounting: 12,
    images: "/products/iphones/ph7/ph7-black.jpg",
    img: "ph7",
    rate:3.5,
    quantity: 0,
  },
  {
    name: "Apple iPhone 8",
    price: 7350,
    colors: ["gold"],
    size: "64",
    memory: "64 ",
    operating_system: "IOS",
    colour: "gold",
    model_year: 2019,
    included: "USB-C ",
    Discounting: 12,
    rate: 3.5,
    img: "ph8",
    images: "/products/iphones/ph8/ph8-gold.jpg",
    quantity: 1,
  },
  {
    name: "Apple iPhone 8 Plus",
    price: 8999,
    colors: ["gold"],
    size: "64",
    memory: "64",
    operating_system: "IOS",
    colour: "gold",
    model_year: 2019,
    included: "USB-C ",
    Discounting: 12,
    rate: 3.5,
    img: "ph8pro",
    images: "/products/iphones/ph8pro/ph8pro-gold.jpg",
    quantity: 10,
  },
  {
    name: "iPhone 11 Pro Max",
    price: 20000,
    colors: ["gold", "green", "silver"],
    size: "512",
    memory: "512 ",
    operating_system: "IOS",
    colour: "gold",
    model_year: 2021,
    included: "USB-C ",
    Discounting: 12,
    rate: 3.5,
    img: "ph11prom",
    images: "/products/iphones/ph11prom/ph11prom-silver.jpg",
    quantity: 6,
  },
];
export default dataIphones;
